LongControlNode:
  ros__parameters:
    auto_enabled: true
    mute: false
    override_absent_joystick: true #FIXME this should be false on the actual car
    #desired_velocity: 17.5
    max_desired_velocity: 62.0
    time_step: 0.01
    throttle:
      proportional_gain: 15.0 # 4.0
      integral_gain: 15.0 # 0.0
      derivative_gain: 0.0
      max_integrator_error: 50.0
      cmd_max: 65.0
      cmd_min: 0.0
      reset_integral_below_this_cmd: 5.0
    brake:
      proportional_gain: 900.0 # 200.0
      integral_gain: 0.01 # 0.005
      derivative_gain: 0.0
      max_integrator_error: 15.0
      park_brake: 300.0
      cmd_max: 1400.0 
      cmd_min: 0.0
      reset_integral_below_this_cmd: 100.0
      vel_error_deadband: 0.5
    gear:
      shift_up: 5000.0
      shift_down: 2200.0
      shift_time_ms: 1000
    max_one_step_long_err_rate: 5000.0 # max allowed one-step change divided by time difference
    max_avg_long_err_rate: 2500.0 # max allowed average change divided by time history duration 
    long_err_history_length: 4 # time history length

# Old params:
# LongControlNode:
#   ros__parameters:
#     auto_enabled: true
#     mute: false
#     override_absent_joystick: true #FIXME this should be false on the actual car
#     #desired_velocity: 17.5
#     max_desired_velocity: 55.0
#     time_step: 0.01
#     throttle:
#       proportional_gain: 6.0 # 4.0
#       integral_gain: 0.5 # 0.0
#       derivative_gain: 0.0
#       max_integrator_error: 10.0
#       cmd_max: 25.0
#       cmd_min: 0.0
#       reset_integral_below_this_cmd: 15.0
#     brake:
#       proportional_gain: 800.0 # 200.0
#       integral_gain: 0.01 # 0.005
#       derivative_gain: 0.0
#       max_integrator_error: 10.0
#       cmd_max: 2000.0 
#       cmd_min: 0.0
#       reset_integral_below_this_cmd: 100.0
#       vel_error_deadband: 0.5
#     gear:
#       shift_up: 4000.0
#       shift_down: 2200.0
#       shift_time_ms: 1000
